[project]
name = "frontend"
version = "0.1.0"
description = "Chainlit frontend for RAG Assistant"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.4.400",
    "httpx>=0.28.1",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]